; version.asm
;
; Auto-generated by ZXVersion.exe
; On 11 Jan 2020 at 15:46

BuildNo                 macro()
                        db "7"
mend

BuildNoValue            equ "7"
BuildNoWidth            equ 0 + FW7



BuildDate               macro()
                        db "11 Jan 2020"
mend

BuildDateValue          equ "11 Jan 2020"
BuildDateWidth          equ 0 + FW1 + FW1 + FWSpace + FWJ + FWa + FWn + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "15:46"
mend

BuildTimeValue          equ "15:46"
BuildTimeWidth          equ 0 + FW1 + FW5 + FWColon + FW4 + FW6



BuildTimeSecs           macro()
                        db "15:46:58"
mend

BuildTimeSecsValue      equ "15:46:58"
BuildTimeSecsWidth      equ 0 + FW1 + FW5 + FWColon + FW4 + FW6 + FWColon + FW5 + FW8
